Testing
Code-the-Dream-School/cc-prac-team1-back pull request #29
Opened 2023-06-22 02:32 UTC by JenMcD-star

When I was doing the testing I noticed the http status code was returning as 500 (which I think would indicate an error on the server) instead of 400 when there was a user error. I updated the middleware folder and app.js with some error handling and that seemed to resolve the problem. 

To run the testing I was using  mocha --timeout 15000.

2023-06-22 10:50 UTC, jamisonvalentine commented
A few comments:

1. It looks like `mocha` isn't listed in your `package.json`. I would recommend install it as a dev dependency and adding that call is a script. 

``` 
"scripts": {
    "dev": "nodemon src/app.js",
    "test": "mocha --timeout 1500"
  },
```

2. One of the tests failed for me when I tried running your branch locally. 

![image](https://github.com/Code-the-Dream-School/cc-prac-team1-back/assets/47033011/ca8889b7-d344-4229-a7fd-2edd57d7274c)


      at C:\Users\jamis\dev\cc-practicum\backend\test\test.js:75:33
      at Request.callback (node_modules\superagent\lib\node\index.js:857:12)
      at C:\Users\jamis\dev\cc-practicum\backend\node_modules\superagent\lib\node\index.js:1070:18
      at IncomingMessage.<anonymous> (node_modules\superagent\lib\node\parsers\json.js:21:7)
      at IncomingMessage.emit (node:events:525:35)
      at endReadableNT (node:internal/streams/readable:1359:12)
      at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

2023-06-22 10:51 UTC, jamisonvalentine requested changes
see other comment

2023-06-22 17:49 UTC, Count-MonteCristo approved these changes
LGTM!

2023-06-23 11:46 UTC, jamisonvalentine approved these changes

2023-06-23 12:30 UTC, merged